// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestingApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;

    /// <summary>
    /// Extension methods for Registration.
    /// </summary>
    public static partial class RegistrationExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userJson'>
            /// </param>
            public static bool? MakeRegistration(this IRegistration operations, string userJson)
            {
                return Task.Factory.StartNew(s => ((IRegistration)s).MakeRegistrationAsync(userJson), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userJson'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<bool?> MakeRegistrationAsync(this IRegistration operations, string userJson, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.MakeRegistrationWithHttpMessagesAsync(userJson, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
